package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 29, 2017 10:42:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventosBuffetsId generated by hbm2java
 */
@Embeddable
public class EventosBuffetsId  implements java.io.Serializable {


     private int eventoId;
     private int buffetId;

    public EventosBuffetsId() {
    }

    public EventosBuffetsId(int eventoId, int buffetId) {
       this.eventoId = eventoId;
       this.buffetId = buffetId;
    }
   


    @Column(name="evento_id", nullable=false)
    public int getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(int eventoId) {
        this.eventoId = eventoId;
    }


    @Column(name="buffet_id", nullable=false)
    public int getBuffetId() {
        return this.buffetId;
    }
    
    public void setBuffetId(int buffetId) {
        this.buffetId = buffetId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventosBuffetsId) ) return false;
		 EventosBuffetsId castOther = ( EventosBuffetsId ) other; 
         
		 return (this.getEventoId()==castOther.getEventoId())
 && (this.getBuffetId()==castOther.getBuffetId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventoId();
         result = 37 * result + this.getBuffetId();
         return result;
   }   


}


