package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 18, 2017 8:46:06 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventosLocais generated by hbm2java
 */
@Entity
@Table(name="eventos_locais"
    ,catalog="gerenciadoreventos"
)
public class EventosLocais  implements java.io.Serializable {


     private EventosLocaisId id;
     private Eventos eventos;
     private Locais locais;
     private BigDecimal valor;

    public EventosLocais() {
    }

    public EventosLocais(EventosLocaisId id, Eventos eventos, Locais locais, BigDecimal valor) {
       this.id = id;
       this.eventos = eventos;
       this.locais = locais;
       this.valor = valor;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="eventoId", column=@Column(name="evento_id", nullable=false) ), 
        @AttributeOverride(name="localId", column=@Column(name="local_id", nullable=false) ) } )
    public EventosLocaisId getId() {
        return this.id;
    }
    
    public void setId(EventosLocaisId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evento_id", nullable=false, insertable=false, updatable=false)
    public Eventos getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Eventos eventos) {
        this.eventos = eventos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="local_id", nullable=false, insertable=false, updatable=false)
    public Locais getLocais() {
        return this.locais;
    }
    
    public void setLocais(Locais locais) {
        this.locais = locais;
    }

    
    @Column(name="valor", nullable=false, precision=15)
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


