package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 18, 2017 8:46:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventosFuncionariosId generated by hbm2java
 */
@Embeddable
public class EventosFuncionariosId  implements java.io.Serializable {


     private int eventoId;
     private int pessoaId;

    public EventosFuncionariosId() {
    }

    public EventosFuncionariosId(int eventoId, int pessoaId) {
       this.eventoId = eventoId;
       this.pessoaId = pessoaId;
    }
   


    @Column(name="evento_id", nullable=false)
    public int getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(int eventoId) {
        this.eventoId = eventoId;
    }


    @Column(name="pessoa_id", nullable=false)
    public int getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventosFuncionariosId) ) return false;
		 EventosFuncionariosId castOther = ( EventosFuncionariosId ) other; 
         
		 return (this.getEventoId()==castOther.getEventoId())
 && (this.getPessoaId()==castOther.getPessoaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventoId();
         result = 37 * result + this.getPessoaId();
         return result;
   }   


}


