package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 29, 2017 10:42:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventosDecoracoesId generated by hbm2java
 */
@Embeddable
public class EventosDecoracoesId  implements java.io.Serializable {


     private int eventoId;
     private int decoracaoId;

    public EventosDecoracoesId() {
    }

    public EventosDecoracoesId(int eventoId, int decoracaoId) {
       this.eventoId = eventoId;
       this.decoracaoId = decoracaoId;
    }
   


    @Column(name="evento_id", nullable=false)
    public int getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(int eventoId) {
        this.eventoId = eventoId;
    }


    @Column(name="decoracao_id", nullable=false)
    public int getDecoracaoId() {
        return this.decoracaoId;
    }
    
    public void setDecoracaoId(int decoracaoId) {
        this.decoracaoId = decoracaoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventosDecoracoesId) ) return false;
		 EventosDecoracoesId castOther = ( EventosDecoracoesId ) other; 
         
		 return (this.getEventoId()==castOther.getEventoId())
 && (this.getDecoracaoId()==castOther.getDecoracaoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventoId();
         result = 37 * result + this.getDecoracaoId();
         return result;
   }   


}


