package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 26, 2017 4:50:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventosAtracoesId generated by hbm2java
 */
@Embeddable
public class EventosAtracoesId  implements java.io.Serializable {


     private int eventoId;
     private int atracaoId;

    public EventosAtracoesId() {
    }

    public EventosAtracoesId(int eventoId, int atracaoId) {
       this.eventoId = eventoId;
       this.atracaoId = atracaoId;
    }
   


    @Column(name="evento_id", nullable=false)
    public int getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(int eventoId) {
        this.eventoId = eventoId;
    }


    @Column(name="atracao_id", nullable=false)
    public int getAtracaoId() {
        return this.atracaoId;
    }
    
    public void setAtracaoId(int atracaoId) {
        this.atracaoId = atracaoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventosAtracoesId) ) return false;
		 EventosAtracoesId castOther = ( EventosAtracoesId ) other; 
         
		 return (this.getEventoId()==castOther.getEventoId())
 && (this.getAtracaoId()==castOther.getAtracaoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventoId();
         result = 37 * result + this.getAtracaoId();
         return result;
   }   


}


