package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 18, 2017 8:46:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locais generated by hbm2java
 */
@Entity
@Table(name="locais"
    ,catalog="gerenciadoreventos"
)
public class Locais  implements java.io.Serializable {


     private Integer id;
     private Contatos contatos;
     private Enderecos enderecos;
     private String nome;
     private int capacidade;
     private Set<EventosLocais> eventosLocaises = new HashSet<EventosLocais>(0);

    public Locais() {
    }

	
    public Locais(Contatos contatos, Enderecos enderecos, String nome, int capacidade) {
        this.contatos = contatos;
        this.enderecos = enderecos;
        this.nome = nome;
        this.capacidade = capacidade;
    }
    public Locais(Contatos contatos, Enderecos enderecos, String nome, int capacidade, Set<EventosLocais> eventosLocaises) {
       this.contatos = contatos;
       this.enderecos = enderecos;
       this.nome = nome;
       this.capacidade = capacidade;
       this.eventosLocaises = eventosLocaises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contato_id", nullable=false)
    public Contatos getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Contatos contatos) {
        this.contatos = contatos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="endereco_id", nullable=false)
    public Enderecos getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Enderecos enderecos) {
        this.enderecos = enderecos;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="capacidade", nullable=false)
    public int getCapacidade() {
        return this.capacidade;
    }
    
    public void setCapacidade(int capacidade) {
        this.capacidade = capacidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="locais")
    public Set<EventosLocais> getEventosLocaises() {
        return this.eventosLocaises;
    }
    
    public void setEventosLocaises(Set<EventosLocais> eventosLocaises) {
        this.eventosLocaises = eventosLocaises;
    }




}


