package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 29, 2017 10:42:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pessoas generated by hbm2java
 */
@Entity
@Table(name="pessoas"
    ,catalog="gerenciadoreventos"
)
public class Pessoas  implements java.io.Serializable {


     private Integer id;
     private Contatos contatos;
     private Enderecos enderecos;
     private String nome;
     private String sobrenome;
     private String cpfCnpj;
     private String rg;
     private Set<EventosFuncionarios> eventosFuncionarioses = new HashSet<EventosFuncionarios>(0);

    public Pessoas() {
    }

	
    public Pessoas(Contatos contatos, Enderecos enderecos, String nome, String sobrenome, String cpfCnpj, String rg) {
        this.contatos = contatos;
        this.enderecos = enderecos;
        this.nome = nome;
        this.sobrenome = sobrenome;
        this.cpfCnpj = cpfCnpj;
        this.rg = rg;
    }
    public Pessoas(Contatos contatos, Enderecos enderecos, String nome, String sobrenome, String cpfCnpj, String rg, Set<EventosFuncionarios> eventosFuncionarioses) {
       this.contatos = contatos;
       this.enderecos = enderecos;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.cpfCnpj = cpfCnpj;
       this.rg = rg;
       this.eventosFuncionarioses = eventosFuncionarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contato_id", nullable=false)
    public Contatos getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Contatos contatos) {
        this.contatos = contatos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="endereco_id", nullable=false)
    public Enderecos getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Enderecos enderecos) {
        this.enderecos = enderecos;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sobrenome", nullable=false, length=100)
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    
    @Column(name="cpf_cnpj", nullable=false, length=30)
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }

    
    @Column(name="rg", nullable=false, length=20)
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoas")
    public Set<EventosFuncionarios> getEventosFuncionarioses() {
        return this.eventosFuncionarioses;
    }
    
    public void setEventosFuncionarioses(Set<EventosFuncionarios> eventosFuncionarioses) {
        this.eventosFuncionarioses = eventosFuncionarioses;
    }




}


