package daniel.lucas.gerenciamentoeventos.entities;
// Generated May 26, 2017 4:50:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Teste generated by hbm2java
 */
@Entity
@Table(name="teste"
    ,catalog="gerenciadoreventos"
)
public class Teste  implements java.io.Serializable {


     private int idteste;
     private String nome;

    public Teste() {
    }

	
    public Teste(int idteste) {
        this.idteste = idteste;
    }
    public Teste(int idteste, String nome) {
       this.idteste = idteste;
       this.nome = nome;
    }
   
     @Id 

    
    @Column(name="idteste", unique=true, nullable=false)
    public int getIdteste() {
        return this.idteste;
    }
    
    public void setIdteste(int idteste) {
        this.idteste = idteste;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


