package entities;
// Generated May 15, 2017 10:59:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Atracoes generated by hbm2java
 */
@Entity
@Table(name="atracoes"
    ,catalog="gerenciadoreventos"
)
public class Atracoes  implements java.io.Serializable {


     private int id;
     private String nome;
     private int contatoId;
     private Integer enderecoId;

    public Atracoes() {
    }

	
    public Atracoes(int id, String nome, int contatoId) {
        this.id = id;
        this.nome = nome;
        this.contatoId = contatoId;
    }
    public Atracoes(int id, String nome, int contatoId, Integer enderecoId) {
       this.id = id;
       this.nome = nome;
       this.contatoId = contatoId;
       this.enderecoId = enderecoId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="contato_id", nullable=false)
    public int getContatoId() {
        return this.contatoId;
    }
    
    public void setContatoId(int contatoId) {
        this.contatoId = contatoId;
    }

    
    @Column(name="endereco_id")
    public Integer getEnderecoId() {
        return this.enderecoId;
    }
    
    public void setEnderecoId(Integer enderecoId) {
        this.enderecoId = enderecoId;
    }




}


