package entities;
// Generated May 15, 2017 10:59:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contatos generated by hbm2java
 */
@Entity
@Table(name="contatos"
    ,catalog="gerenciadoreventos"
)
public class Contatos  implements java.io.Serializable {


     private int id;
     private String telefone;
     private String celular;
     private String whatsapp;

    public Contatos() {
    }

    public Contatos(int id, String telefone, String celular, String whatsapp) {
       this.id = id;
       this.telefone = telefone;
       this.celular = celular;
       this.whatsapp = whatsapp;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="telefone", nullable=false, length=30)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="celular", nullable=false, length=30)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="whatsapp", nullable=false, length=30)
    public String getWhatsapp() {
        return this.whatsapp;
    }
    
    public void setWhatsapp(String whatsapp) {
        this.whatsapp = whatsapp;
    }




}


