package entities;
// Generated May 15, 2017 10:59:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Enderecos generated by hbm2java
 */
@Entity
@Table(name="enderecos"
    ,catalog="gerenciadoreventos"
)
public class Enderecos  implements java.io.Serializable {


     private int id;
     private String cep;
     private String rua;
     private String bairro;
     private String cidade;
     private String uf;
     private String numero;

    public Enderecos() {
    }

    public Enderecos(int id, String cep, String rua, String bairro, String cidade, String uf, String numero) {
       this.id = id;
       this.cep = cep;
       this.rua = rua;
       this.bairro = bairro;
       this.cidade = cidade;
       this.uf = uf;
       this.numero = numero;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="cep", nullable=false, length=9)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="rua", nullable=false, length=100)
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }

    
    @Column(name="bairro", nullable=false, length=100)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", nullable=false, length=100)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="uf", nullable=false, length=2)
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }

    
    @Column(name="numero", nullable=false, length=11)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


