package entities;
// Generated May 15, 2017 10:59:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Eventos generated by hbm2java
 */
@Entity
@Table(name="eventos"
    ,catalog="gerenciadoreventos"
)
public class Eventos  implements java.io.Serializable {


     private int id;
     private String nome;
     private Date dataInicio;
     private Date dataTermino;
     private Date criadoEm;

    public Eventos() {
    }

    public Eventos(int id, String nome, Date dataInicio, Date dataTermino, Date criadoEm) {
       this.id = id;
       this.nome = nome;
       this.dataInicio = dataInicio;
       this.dataTermino = dataTermino;
       this.criadoEm = criadoEm;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_inicio", nullable=false, length=19)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_termino", nullable=false, length=19)
    public Date getDataTermino() {
        return this.dataTermino;
    }
    
    public void setDataTermino(Date dataTermino) {
        this.dataTermino = dataTermino;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="criado_em", nullable=false, length=19)
    public Date getCriadoEm() {
        return this.criadoEm;
    }
    
    public void setCriadoEm(Date criadoEm) {
        this.criadoEm = criadoEm;
    }




}


