package entities;
// Generated May 15, 2017 10:59:13 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Locais generated by hbm2java
 */
@Entity
@Table(name="locais"
    ,catalog="gerenciadoreventos"
)
public class Locais  implements java.io.Serializable {


     private int id;
     private String nome;
     private int capacidade;
     private int enderecoId;
     private int contatoId;

    public Locais() {
    }

    public Locais(int id, String nome, int capacidade, int enderecoId, int contatoId) {
       this.id = id;
       this.nome = nome;
       this.capacidade = capacidade;
       this.enderecoId = enderecoId;
       this.contatoId = contatoId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="capacidade", nullable=false)
    public int getCapacidade() {
        return this.capacidade;
    }
    
    public void setCapacidade(int capacidade) {
        this.capacidade = capacidade;
    }

    
    @Column(name="endereco_id", nullable=false)
    public int getEnderecoId() {
        return this.enderecoId;
    }
    
    public void setEnderecoId(int enderecoId) {
        this.enderecoId = enderecoId;
    }

    
    @Column(name="contato_id", nullable=false)
    public int getContatoId() {
        return this.contatoId;
    }
    
    public void setContatoId(int contatoId) {
        this.contatoId = contatoId;
    }




}


