/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package daniel.lucas.gerenciamentoeventos.forms;

import daniel.lucas.gerenciamentoeventos.controller.ControllerContatos;
import daniel.lucas.gerenciamentoeventos.controller.ControllerEndereco;
import daniel.lucas.gerenciamentoeventos.controller.ControllerPessoas;
import daniel.lucas.gerenciamentoeventos.entities.Contatos;
import daniel.lucas.gerenciamentoeventos.entities.Enderecos;
import daniel.lucas.gerenciamentoeventos.entities.Pessoas;
import daniel.lucas.gerenciamentoeventos.utils.CorPainelSelecionado;
import static daniel.lucas.gerenciamentoeventos.utils.Messagens.*;

//import static daniel.lucas.gerenciamentoeventos.validador.ValidadorEndereco.popularNomeCamposObrigatorios;

//import static daniel.lucas.gerenciamentoeventos.validador.ValidadorPessoa.popularNomeCamposObrigatorios;

import daniel.lucas.gerenciamentoeventos.validador.Validador;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author aluno
 */
public class JanelaCadastroPessoa extends javax.swing.JFrame implements CorPainelSelecionado {

    /**
     * Creates new form JanelaCadastroPessoa
     */
    public JanelaCadastroPessoa() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.DARK_GRAY);
        setarCoresIcones();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TFTelefone = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("(##) ####-####");
            TFTelefone = new javax.swing.JFormattedTextField(telefone);
            TFTelefone.setBackground(new java.awt.Color(51, 51, 51));
            TFTelefone.setForeground(new java.awt.Color(204, 204, 204));
            TFTelefone.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
            TFTelefone.setCaretColor(null);
        }catch(Exception e){

        }
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TFNome = new javax.swing.JTextField();
        TFSobrenome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TFRg = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter rg = new javax.swing.text.MaskFormatter("###.###.###-#");

            TFRg = new javax.swing.JFormattedTextField(rg);
            TFRg.setBackground(new java.awt.Color(51, 51, 51));
            TFRg.setForeground(new java.awt.Color(204, 204, 204));
            TFRg.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
            TFRg.setCaretColor(null);
        }catch(Exception e){
        }
        jLabel12 = new javax.swing.JLabel();
        TFCpf = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter cpfCnpj;

            if(TFCpf.getText().length() < 10)
            cpfCnpj = new javax.swing.text.MaskFormatter("###.###.##-##");
            else
            cpfCnpj = new javax.swing.text.MaskFormatter("##.###.###/###-##");

            TFCpf = new javax.swing.JFormattedTextField(cpfCnpj);
            TFCpf.setBackground(new java.awt.Color(51, 51, 51));
            TFCpf.setForeground(new java.awt.Color(204, 204, 204));
            TFCpf.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
            TFCpf.setCaretColor(null);
        }catch(Exception e){
        }
        TFWhatsApp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        TFRua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TFNumero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TFBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TFCidade = new javax.swing.JTextField();
        CBUf = new javax.swing.JComboBox<>();
        TFCep = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        TFFuncao = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TFSalario = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Colaborador");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane5.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane5.setForeground(new java.awt.Color(204, 204, 204));
        jTabbedPane5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(64, 64, 64));
        jPanel4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel4ComponentShown(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("CPF/CNPJ:*");

        TFTelefone.setBackground(new java.awt.Color(51, 51, 51));
        TFTelefone.setForeground(new java.awt.Color(204, 204, 204));
        TFTelefone.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFTelefone.setCaretColor(null);

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Telefone:");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Celular:");

        TFCelular.setBackground(new java.awt.Color(51, 51, 51));
        TFCelular.setForeground(new java.awt.Color(204, 204, 204));
        TFCelular.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFCelular.setCaretColor(null);
        try{
            javax.swing.text.MaskFormatter celular = new javax.swing.text.MaskFormatter("(##) #####-####");
            TFCelular = new javax.swing.JFormattedTextField(celular);
            TFCelular.setBackground(new java.awt.Color(51, 51, 51));
            TFCelular.setForeground(new java.awt.Color(204, 204, 204));
            TFCelular.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
            TFCelular.setCaretColor(null);
        }catch(Exception e){

        }

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nome:*");

        TFNome.setBackground(new java.awt.Color(51, 51, 51));
        TFNome.setForeground(new java.awt.Color(204, 204, 204));
        TFNome.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFNome.setCaretColor(null);

        TFSobrenome.setBackground(new java.awt.Color(51, 51, 51));
        TFSobrenome.setForeground(new java.awt.Color(204, 204, 204));
        TFSobrenome.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFSobrenome.setCaretColor(null);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Sobrenome:*");

        TFRg.setBackground(new java.awt.Color(51, 51, 51));
        TFRg.setForeground(new java.awt.Color(204, 204, 204));
        TFRg.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFRg.setCaretColor(null);

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("RG:");

        TFCpf.setBackground(new java.awt.Color(51, 51, 51));
        TFCpf.setForeground(new java.awt.Color(204, 204, 204));
        TFCpf.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFCpf.setCaretColor(null);

        TFWhatsApp.setBackground(new java.awt.Color(51, 51, 51));
        TFWhatsApp.setForeground(new java.awt.Color(204, 204, 204));
        TFWhatsApp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFWhatsApp.setCaretColor(null);

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("WhatsApp:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFSobrenome)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TFCelular)))
                            .addComponent(TFNome)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFRg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TFCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFWhatsApp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25)))
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFWhatsApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Pessoa", jPanel4);

        jPanel5.setBackground(new java.awt.Color(64, 64, 64));
        jPanel5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel5ComponentShown(evt);
            }
        });

        TFRua.setBackground(new java.awt.Color(51, 51, 51));
        TFRua.setForeground(new java.awt.Color(204, 204, 204));
        TFRua.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFRua.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Rua:");

        TFNumero.setBackground(new java.awt.Color(51, 51, 51));
        TFNumero.setForeground(new java.awt.Color(204, 204, 204));
        TFNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFNumero.setCaretColor(new java.awt.Color(255, 255, 255));
        TFNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFNumeroKeyTyped(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Numero:");

        TFBairro.setBackground(new java.awt.Color(51, 51, 51));
        TFBairro.setForeground(new java.awt.Color(204, 204, 204));
        TFBairro.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFBairro.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Bairro:");

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Cidade:");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("UF:");

        TFCidade.setBackground(new java.awt.Color(51, 51, 51));
        TFCidade.setForeground(new java.awt.Color(204, 204, 204));
        TFCidade.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFCidade.setCaretColor(new java.awt.Color(255, 255, 255));

        CBUf.setBackground(new java.awt.Color(64, 64, 64));
        CBUf.setForeground(new java.awt.Color(204, 204, 204));
        CBUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "TO", " " }));
        CBUf.setSelectedIndex(26);

        TFCep.setBackground(new java.awt.Color(51, 51, 51));
        TFCep.setForeground(new java.awt.Color(204, 204, 204));
        TFCep.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFCep.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("CEP:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFRua)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(TFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFNumero)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 15, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFCidade)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(TFCep, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Endereço", jPanel5);

        jPanel6.setBackground(new java.awt.Color(64, 64, 64));
        jPanel6.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel6ComponentShown(evt);
            }
        });

        TFFuncao.setBackground(new java.awt.Color(51, 51, 51));
        TFFuncao.setForeground(new java.awt.Color(204, 204, 204));
        TFFuncao.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFFuncao.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Função:");

        TFSalario.setBackground(new java.awt.Color(51, 51, 51));
        TFSalario.setForeground(new java.awt.Color(204, 204, 204));
        TFSalario.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        TFSalario.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Salario:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFFuncao)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(TFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 286, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Função", jPanel6);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(204, 204, 204));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        confirmacaoCancelar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
        controllerPessoas = new ControllerPessoas();
        
        inserir(popularEnderecos(), popularContatos(), popularPessoa());
    }//GEN-LAST:event_jButton1ActionPerformed

    private String popularStringBuilder(List<String> lista){
        StringBuilder sb = new StringBuilder();
            lista.forEach(campo->{
                    sb.append(campo + ", ");
                });
        return sb.toString();
    }
    
    private void inserir(List<String> camposObrigatoriosEndereco, List<String> camposObrigatoriosContatos, List<String> camposObrigatoriosPessoas) {

        if(camposObrigatoriosEndereco.size() > 0 || camposObrigatoriosContatos.size() > 0 || camposObrigatoriosPessoas.size() > 0){
            
            StringBuilder sb = new StringBuilder();
           
            sb.append(camposObrigatoriosEndereco.size() == 1 || camposObrigatoriosContatos.size() == 1 || camposObrigatoriosPessoas.size() == 1 ? 
                    "O campo " + popularStringBuilder(camposObrigatoriosEndereco) +  popularStringBuilder(camposObrigatoriosContatos) + popularStringBuilder(camposObrigatoriosPessoas) +"é obrigatório!" :
                    "Os campos "+ popularStringBuilder(camposObrigatoriosEndereco) +  popularStringBuilder(camposObrigatoriosContatos) + popularStringBuilder(camposObrigatoriosPessoas) +"são obrigatórios!");
            
            error(sb.toString());

        }else{
            String retorno = controllerPessoas.insert();
            
            switch(retorno){
                case "success":
                    success("Colaborador cadastrado com sucesso!");
                    break;
                case "error":
                    error("Colaborador não cadastrado!");
                    break;
                default:
                    error("Erro ao cadastrar!");
                    break;
            }
            
        }
    }

    private List<String> popularEnderecos() {
        
        controllerPessoas.enderecos.setCep(TFCep.getText());
        controllerPessoas.enderecos.setRua(TFRua.getText());
        controllerPessoas.enderecos.setBairro(TFBairro.getText());
        controllerPessoas.enderecos.setCidade(TFCidade.getText());
        controllerPessoas.enderecos.setUf(CBUf.getItemAt(CBUf.getSelectedIndex()));
        controllerPessoas.enderecos.setNumero(TFNumero.getText());

        Validador validador = new Validador(Enderecos.class);
   
        return validador.validarEntity(controllerPessoas.enderecos);
    }
    
    private List<String> popularContatos() {
        controllerPessoas.contatos.setCelular(TFCelular.getText());
        controllerPessoas.contatos.setTelefone(TFTelefone.getText());
        controllerPessoas.contatos.setWhatsapp(TFWhatsApp.getText());
        
        Validador validador = new Validador(Contatos.class);
   
        return validador.validarEntity(controllerPessoas.contatos);
    }
    
    private List<String> popularPessoa() {
        
        controllerPessoas.pessoas.setNome(TFNome.getText());;
        controllerPessoas.pessoas.setSobrenome(TFSobrenome.getText());
        controllerPessoas.pessoas.setCpfCnpj(TFCpf.getText());
        controllerPessoas.pessoas.setRg(TFRg.getText());
        
        Validador validador = new Validador(Pessoas.class);
   
        return validador.validarEntity(controllerPessoas.pessoas);
    }
   

    private void jPanel5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel5ComponentShown
        panelColorSeleciodado(jTabbedPane5);
    }//GEN-LAST:event_jPanel5ComponentShown

    private void jPanel4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel4ComponentShown
       panelColorSeleciodado(jTabbedPane5);
    }//GEN-LAST:event_jPanel4ComponentShown

    private void TFNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFNumeroKeyTyped
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }

    }//GEN-LAST:event_TFNumeroKeyTyped

    private void jPanel6ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel6ComponentShown
        panelColorSeleciodado(jTabbedPane5);
    }//GEN-LAST:event_jPanel6ComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBUf;
    private javax.swing.JTextField TFBairro;
    private javax.swing.JTextField TFCelular;
    private javax.swing.JTextField TFCep;
    private javax.swing.JTextField TFCidade;
    private javax.swing.JTextField TFCpf;
    private javax.swing.JTextField TFFuncao;
    private javax.swing.JTextField TFNome;
    private javax.swing.JTextField TFNumero;
    private javax.swing.JTextField TFRg;
    private javax.swing.JTextField TFRua;
    private javax.swing.JTextField TFSalario;
    private javax.swing.JTextField TFSobrenome;
    private javax.swing.JTextField TFTelefone;
    private javax.swing.JTextField TFWhatsApp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane5;
    // End of variables declaration//GEN-END:variables
//    ControllerEndereco controllerEndereco;
//    ControllerContatos controllerContatos;
    ControllerPessoas controllerPessoas;
    
    @Override
    public void panelColorSeleciodado(JTabbedPane jTabbedPanel) {
        Color color = new Color(187,187,187);
        
        for (int i = 0; i < jTabbedPanel.getTabCount(); i++) {
            jTabbedPanel.setForegroundAt(i, color);
        
        }
        
        jTabbedPanel.setForegroundAt(jTabbedPanel.getSelectedIndex(), Color.BLACK);
    }

    private void setarCoresIcones() {
        
        setarIcones(jButton1, IconFontSwing.buildIcon(FontAwesome.FLOPPY_O, 20, new Color(0, 150, 90)));
        setarIcones(jButton2, IconFontSwing.buildIcon(FontAwesome.TIMES, 20, new Color(255, 90, 90)));
  
    }

    @Override
    public void setarIcones(JButton jButton, Icon icon ) { 
        jButton.setIcon(icon);
        jButton.setFocusable(false);
    }

    @Override
    public void confirmacaoCancelar() {
        String[] buttons = { "Sim", "Não", "Cancelar" };
        if(JOptionPane.showOptionDialog(null, "Deseja realmente sair?", "Confirmação",
        JOptionPane.WARNING_MESSAGE, 0, null, buttons, buttons[1]) == 1){
            this.dispose();
        }
    }

}
